"""empty message

Revision ID: 736fdec882de
Revises: 8d146c2e94a3
Create Date: 2017-03-13 22:23:09.348156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736fdec882de'
down_revision = '8d146c2e94a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('username', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'username')
    # ### end Alembic commands ###
